name = input("enter a name ")
namedos = input("enter a second name ")
place = input("enter a place ")
verb = input("enter a verb ")
print(name + " and " + namedos + " went to " + place + " so they could " + verb + ".")